/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { CategoriesControllerFindAllSortBy } from './categoriesControllerFindAllSortBy';
import type { CategoriesControllerFindAllSortOrder } from './categoriesControllerFindAllSortOrder';

export type CategoriesControllerFindAllParams = {
/**
 * Número da página
 * @minimum 1
 */
page?: number;
/**
 * Itens por página
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
/**
 * Termo de busca
 * @maxLength 120
 */
search?: string;
/**
 * Campo de ordenação
 */
sortBy?: CategoriesControllerFindAllSortBy;
/**
 * Direção da ordenação
 */
sortOrder?: CategoriesControllerFindAllSortOrder;
};
