/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export type CategoriesControllerFindAllSortOrder = typeof CategoriesControllerFindAllSortOrder[keyof typeof CategoriesControllerFindAllSortOrder];


export const CategoriesControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
