/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export type CategoriesControllerFindAllSortBy = typeof CategoriesControllerFindAllSortBy[keyof typeof CategoriesControllerFindAllSortBy];


export const CategoriesControllerFindAllSortBy = {
  name: 'name',
  createdAt: 'createdAt',
} as const;
