/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { PaginationMetaDto } from './paginationMetaDto';

export interface PaginatedCategoriesResponseDto {
  /** Lista de categorias paginadas */
  data: CategoryDto[];
  /** Metadados de paginação */
  meta: PaginationMetaDto;
}
