/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { TaskCategoryDto } from './taskCategoryDto';
import type { TaskDtoDescription } from './taskDtoDescription';
import type { TaskDtoDueDate } from './taskDtoDueDate';
import type { TaskDtoPriority } from './taskDtoPriority';
import type { TaskDtoStatus } from './taskDtoStatus';
import type { TaskOwnerDto } from './taskOwnerDto';

export interface TaskDto {
  /** Identificador único da tarefa */
  id: string;
  /** Título da tarefa */
  title: string;
  /**
     * Descrição da tarefa
     * @nullable
     */
  description?: TaskDtoDescription;
  /** Status da tarefa */
  status: TaskDtoStatus;
  /** Prioridade da tarefa */
  priority: TaskDtoPriority;
  /**
     * Data limite de entrega
     * @nullable
     */
  dueDate?: TaskDtoDueDate;
  /** Identificador do usuário proprietário */
  ownerId: string;
  /** Dados resumidos do proprietário */
  owner?: TaskOwnerDto;
  /**
     * Identificador da categoria
     * @nullable
     */
  categoryId?: string | null;
  /**
     * Dados resumidos da categoria
     * @nullable
     */
  category?: TaskCategoryDto | null;
  /** Data de criação */
  createdAt: string;
  /** Data de última atualização */
  updatedAt: string;
}
