/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export interface TaskCategoryDto {
  /** Identificador único da categoria */
  id: string;
  /** Nome da categoria */
  name: string;
  /** Cor da categoria em hexadecimal */
  color: string;
}
